name: 'Discover Platforms'
inputs:
  password:
    required: true
  package-name:
    required: true
  platform-files:
    required: true
outputs:
  platforms:
    description: 'Object with all platforms discovered and their ghcr image & tag'
  platform-list:
    description: 'Just the keys from the above object'
  missing-platforms:
    description: 'Array of platforms missing from ghcr (i.e. dockerfiles that need to be built)'
runs:
  using: 'node20'
  main: 'dist/index.mjs'
